# This is a basic workflow to help you get started with Actions
name: Build Multiplatform Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  push:
    branches: ['release/**']
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createWindowsRelease:
    uses: ./.github/workflows/build-windows.yml

  createMacOsRelease:
    uses: ./.github/workflows/build-macOS.yml

  releaseArtifactsOnGithubRelease:
    runs-on: ubuntu-latest
    needs:
      - createWindowsRelease
      - createMacOsRelease
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v0.1.0-alpha composeApp/build/compose/binaries/main-release/app/dmg/de.hive.gamefinder-1.0.0.dmg
          gh release upload v0.1.0-alpha composeApp/build/compose/binaries/main-release/app/dmg/de.hive.gamefinder-0.1.0.msi


