name: Release Build Artifacts on Github

on:
  workflow_run:
    workflows: [Build Multiplatform Project]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4

      - name: Upload to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/main-release/app/dmg/de.hive.gamefinder-1.0.0.dmg
            composeApp/build/compose/binaries/main-release/app/msi/de.hive.gamefinder-0.1.0.msi