name: JetBrains Runtime Setup

on:
  workflow_call:

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Install and Setup JetBrains Runtime (Windows)
        shell: bash
        env:
          JBR_URL_Windows_X64: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr-17.0.10-windows-x64-b1000.48.tar.gz'
        run: |
              choco install wget -y
              mkdir -p "$HOME/.jdks/jbr17"
              wget -q -O - "$JBR_URL_${{ runner.os }}_${{ runner.arch }}" | tar -xzf - --strip-components=1 -C "$HOME/.jdks/jbr17"

      - name: Setup JAVA_HOME and PATH (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
              echo "JAVA_HOME=$HOME\.jdks\jbr17" >> $env:GITHUB_ENV
              echo "PATH=$HOME\.jdks\jbr17\bin;$env:PATH" >> $env:GITHUB_ENV